# Generated by Django 5.2.4 on 2025-10-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('genres', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
